#!/usr/bin/env bash
# Populates derived env files from `.env.bootstrap`. Idempotent — safe to re-run.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOOTSTRAP="$ROOT/.env.bootstrap"

if [ ! -f "$BOOTSTRAP" ]; then
  echo "ERROR: $BOOTSTRAP not found. Copy .env.bootstrap.example or follow section 4.6 of the execution plan." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
. "$BOOTSTRAP"
set +a

require() {
  local var="$1"
  if [ -z "${!var:-}" ]; then
    echo "ERROR: required variable $var is empty in .env.bootstrap" >&2
    exit 1
  fi
}

for v in GITHUB_REPO SUPABASE_ACCESS_TOKEN SUPABASE_DEV_PROJECT_REF \
         SUPABASE_PROD_PROJECT_REF SUPABASE_DEV_DB_PASSWORD SUPABASE_PROD_DB_PASSWORD \
         VERCEL_TOKEN VERCEL_ORG_ID VERCEL_PROJECT_ID CLOUDFLARE_API_TOKEN \
         CLOUDFLARE_ZONE_ID MS_CLIENT_ID MS_CLIENT_SECRET MS_DEV_TENANT_ID \
         TF_STATE_KEY; do
  require "$v"
done

# ─── .env.local (consumed by `next dev` and `supabase start`) ───────────────────
cat > "$ROOT/.env.local" <<EOF
# AUTO-GENERATED by scripts/dev-bootstrap.sh. Do not edit by hand.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
MS_CLIENT_ID=$MS_CLIENT_ID
MS_CLIENT_SECRET=$MS_CLIENT_SECRET
MS_DEV_TENANT_ID=$MS_DEV_TENANT_ID
EMAIL_DRIVER=mailpit
EOF
echo "✓ wrote .env.local"

# ─── infra/envs/dev.tfvars ──────────────────────────────────────────────────────
mkdir -p "$ROOT/infra/envs"
cat > "$ROOT/infra/envs/dev.tfvars" <<EOF
env = "dev"

supabase_access_token = "$SUPABASE_ACCESS_TOKEN"
supabase_project_ref  = "$SUPABASE_DEV_PROJECT_REF"
supabase_db_password  = "$SUPABASE_DEV_DB_PASSWORD"
supabase_region       = "eu-west-2"

vercel_token      = "$VERCEL_TOKEN"
vercel_org_id     = "$VERCEL_ORG_ID"
vercel_project_id = "$VERCEL_PROJECT_ID"

cloudflare_api_token = "$CLOUDFLARE_API_TOKEN"
cloudflare_zone_id   = "$CLOUDFLARE_ZONE_ID"
app_subdomain        = ""

ms_client_id     = "$MS_CLIENT_ID"
ms_client_secret = "$MS_CLIENT_SECRET"
EOF
echo "✓ wrote infra/envs/dev.tfvars"

# ─── infra/envs/prod.tfvars ─────────────────────────────────────────────────────
cat > "$ROOT/infra/envs/prod.tfvars" <<EOF
env = "prod"

supabase_access_token = "$SUPABASE_ACCESS_TOKEN"
supabase_project_ref  = "$SUPABASE_PROD_PROJECT_REF"
supabase_db_password  = "$SUPABASE_PROD_DB_PASSWORD"
supabase_region       = "eu-west-2"

vercel_token      = "$VERCEL_TOKEN"
vercel_org_id     = "$VERCEL_ORG_ID"
vercel_project_id = "$VERCEL_PROJECT_ID"

cloudflare_api_token = "$CLOUDFLARE_API_TOKEN"
cloudflare_zone_id   = "$CLOUDFLARE_ZONE_ID"
app_subdomain        = "outreach"

ms_client_id     = "$MS_CLIENT_ID"
ms_client_secret = "$MS_CLIENT_SECRET"
EOF
echo "✓ wrote infra/envs/prod.tfvars"

echo
echo "Bootstrap complete. Next: \`make dev\` or \`make dev-docker\`."
