Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Populates `.env.local` for LOCAL development from `.env.bootstrap`. Idempotent.
#
# Local development runs against a Docker Postgres 16 + Mailpit (see
# docker-compose.dev.yml) — no Supabase CLI, no cloud project. The only operator
# values consumed here are the Microsoft app-registration ones, which feed the
# Auth.js Entra provider (mapped to AZURE_AD_*).
#
# Cloud/prod infrastructure values live in scripts/bootstrap-prod.ps1, which
# generates infra/envs/prod.tfvars.

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$Bootstrap = Join-Path $Root '.env.bootstrap'

if (-not (Test-Path -LiteralPath $Bootstrap)) {
  throw "ERROR: $Bootstrap not found. Copy .env.bootstrap.example or follow section 4.6 of the execution plan."
}

. (Join-Path $PSScriptRoot 'lib/load-dotenv.ps1')
$Vars = Read-DotenvFile -Path $Bootstrap

function Require-BootstrapValue {
  param([Parameter(Mandatory = $true)][string] $Name)

  if (-not $Vars.ContainsKey($Name) -or [string]::IsNullOrWhiteSpace($Vars[$Name])) {
    throw "ERROR: required variable $Name is empty in .env.bootstrap (local dev needs the Microsoft values for the Auth.js Entra provider)."
  }
}

@(
  'MS_CLIENT_ID',
  'MS_CLIENT_SECRET',
  'MS_DEV_TENANT_ID'
) | ForEach-Object { Require-BootstrapValue $_ }

# Windows PowerShell 5.1's Set-Content defaults to UTF-16LE, which Docker
# Compose (--env-file) cannot parse. Write UTF-8 without a BOM.
function Write-Utf8NoBom {
  param(
    [Parameter(Mandatory = $true)][string] $Path,
    [Parameter(Mandatory = $true)][string] $Content
  )
  [System.IO.File]::WriteAllText($Path, $Content + "`n", (New-Object System.Text.UTF8Encoding($false)))
}

# The Postgres credentials below are the deterministic local-stack defaults
# (not secrets) — they match docker-compose.dev.yml.
$EnvLocal = @"
# AUTO-GENERATED by scripts/dev-bootstrap.ps1. Do not edit by hand.
DATABASE_URL=postgres://app_user:apppw@localhost:5433/outreach
DATABASE_URL_ADMIN=postgres://postgres:postgres@localhost:5433/outreach
# DATABASE_URL_TEST=postgres://app_user:apppw@localhost:5433/outreach  # Uncomment to run DB integration tests
APP_USER_PASSWORD=apppw
PGSSL=disable
AUTH_SECRET=dev-insecure-local-secret
AZURE_AD_CLIENT_ID=$($Vars['MS_CLIENT_ID'])
AZURE_AD_CLIENT_SECRET=$($Vars['MS_CLIENT_SECRET'])
AZURE_AD_TENANT_ID=$($Vars['MS_DEV_TENANT_ID'])
EMAIL_DRIVER=mailpit
APP_BASE_URL=http://localhost:3000
# Local dev only: enables the /auth/mock dev sign-in. NODE_ENV=production ignores it.
AUTH_MOCK_ENABLED=true
"@

Write-Utf8NoBom -Path (Join-Path $Root '.env.local') -Content $EnvLocal
Write-Host 'wrote .env.local'
Write-Host ''
Write-Host 'Local bootstrap complete. Next: make dev.'
Write-Host 'For the prod cloud environment (Azure), run ./scripts/bootstrap-prod.ps1.'
