Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Populates `.env.local` for LOCAL development from `.env.bootstrap`. Idempotent.
#
# Local development needs NO Supabase cloud project and NO Vercel — the stack
# runs entirely on the local Supabase CLI (`supabase start`). The only operator
# values consumed here are the Microsoft app-registration ones, because the
# local Supabase Auth has the Azure provider enabled (see supabase/config.toml).
#
# Cloud/prod infrastructure values live in scripts/bootstrap-prod.ps1, which
# generates infra/envs/prod.tfvars.

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$Bootstrap = Join-Path $Root '.env.bootstrap'

if (-not (Test-Path -LiteralPath $Bootstrap)) {
  throw "ERROR: $Bootstrap not found. Copy .env.bootstrap.example or follow section 4.6 of the execution plan."
}

. (Join-Path $PSScriptRoot 'lib/load-dotenv.ps1')
$Vars = Read-DotenvFile -Path $Bootstrap

function Require-BootstrapValue {
  param([Parameter(Mandatory = $true)][string] $Name)

  if (-not $Vars.ContainsKey($Name) -or [string]::IsNullOrWhiteSpace($Vars[$Name])) {
    throw "ERROR: required variable $Name is empty in .env.bootstrap (local dev needs the Microsoft values so 'supabase start' can enable the Azure auth provider)."
  }
}

@(
  'MS_CLIENT_ID',
  'MS_CLIENT_SECRET',
  'MS_DEV_TENANT_ID'
) | ForEach-Object { Require-BootstrapValue $_ }

# Windows PowerShell 5.1's Set-Content defaults to UTF-16LE, which Docker
# Compose (--env-file) cannot parse. Write UTF-8 without a BOM.
function Write-Utf8NoBom {
  param(
    [Parameter(Mandatory = $true)][string] $Path,
    [Parameter(Mandatory = $true)][string] $Content
  )
  [System.IO.File]::WriteAllText($Path, $Content + "`n", (New-Object System.Text.UTF8Encoding($false)))
}

# The Supabase URL and keys below are the deterministic local-stack defaults
# (not secrets) — no cloud project is involved.
$EnvLocal = @"
# AUTO-GENERATED by scripts/dev-bootstrap.ps1. Do not edit by hand.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
MS_CLIENT_ID=$($Vars['MS_CLIENT_ID'])
MS_CLIENT_SECRET=$($Vars['MS_CLIENT_SECRET'])
MS_DEV_TENANT_ID=$($Vars['MS_DEV_TENANT_ID'])
EMAIL_DRIVER=mailpit
"@

Write-Utf8NoBom -Path (Join-Path $Root '.env.local') -Content $EnvLocal
Write-Host 'wrote .env.local'
Write-Host ''
Write-Host 'Local bootstrap complete. Next: make dev or ./scripts/dev-docker.ps1.'
Write-Host 'For the prod cloud environment (Supabase + Vercel), run ./scripts/bootstrap-prod.ps1.'
