Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$Bootstrap = Join-Path $Root '.env.bootstrap'

if (-not (Test-Path -LiteralPath $Bootstrap)) {
  throw "ERROR: $Bootstrap not found. Copy .env.bootstrap.example or follow section 4.6 of the execution plan."
}

. (Join-Path $PSScriptRoot 'lib/load-dotenv.ps1')
$Vars = Read-DotenvFile -Path $Bootstrap

function Require-BootstrapValue {
  param([Parameter(Mandatory = $true)][string] $Name)

  if (-not $Vars.ContainsKey($Name) -or [string]::IsNullOrWhiteSpace($Vars[$Name])) {
    throw "ERROR: required variable $Name is empty in .env.bootstrap"
  }
}

@(
  'GITHUB_REPO',
  'SUPABASE_ACCESS_TOKEN',
  'SUPABASE_DEV_PROJECT_REF',
  'SUPABASE_PROD_PROJECT_REF',
  'SUPABASE_DEV_DB_PASSWORD',
  'SUPABASE_PROD_DB_PASSWORD',
  'VERCEL_TOKEN',
  'VERCEL_ORG_ID',
  'VERCEL_PROJECT_ID',
  'CLOUDFLARE_API_TOKEN',
  'CLOUDFLARE_ZONE_ID',
  'MS_CLIENT_ID',
  'MS_CLIENT_SECRET',
  'MS_DEV_TENANT_ID',
  'TF_STATE_KEY'
) | ForEach-Object { Require-BootstrapValue $_ }

$EnvLocal = @"
# AUTO-GENERATED by scripts/dev-bootstrap.ps1. Do not edit by hand.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
MS_CLIENT_ID=$($Vars['MS_CLIENT_ID'])
MS_CLIENT_SECRET=$($Vars['MS_CLIENT_SECRET'])
MS_DEV_TENANT_ID=$($Vars['MS_DEV_TENANT_ID'])
EMAIL_DRIVER=mailpit
"@

Set-Content -LiteralPath (Join-Path $Root '.env.local') -Value $EnvLocal
Write-Host 'wrote .env.local'

$EnvDir = Join-Path $Root 'infra/envs'
New-Item -ItemType Directory -Force -Path $EnvDir | Out-Null

$DevTfvars = @"
env = "dev"

supabase_access_token = "$($Vars['SUPABASE_ACCESS_TOKEN'])"
supabase_project_ref  = "$($Vars['SUPABASE_DEV_PROJECT_REF'])"
supabase_db_password  = "$($Vars['SUPABASE_DEV_DB_PASSWORD'])"
supabase_region       = "eu-west-2"

vercel_token      = "$($Vars['VERCEL_TOKEN'])"
vercel_org_id     = "$($Vars['VERCEL_ORG_ID'])"
vercel_project_id = "$($Vars['VERCEL_PROJECT_ID'])"

cloudflare_api_token = "$($Vars['CLOUDFLARE_API_TOKEN'])"
cloudflare_zone_id   = "$($Vars['CLOUDFLARE_ZONE_ID'])"
app_subdomain        = ""

ms_client_id     = "$($Vars['MS_CLIENT_ID'])"
ms_client_secret = "$($Vars['MS_CLIENT_SECRET'])"
"@

Set-Content -LiteralPath (Join-Path $EnvDir 'dev.tfvars') -Value $DevTfvars
Write-Host 'wrote infra/envs/dev.tfvars'

$ProdTfvars = @"
env = "prod"

supabase_access_token = "$($Vars['SUPABASE_ACCESS_TOKEN'])"
supabase_project_ref  = "$($Vars['SUPABASE_PROD_PROJECT_REF'])"
supabase_db_password  = "$($Vars['SUPABASE_PROD_DB_PASSWORD'])"
supabase_region       = "eu-west-2"

vercel_token      = "$($Vars['VERCEL_TOKEN'])"
vercel_org_id     = "$($Vars['VERCEL_ORG_ID'])"
vercel_project_id = "$($Vars['VERCEL_PROJECT_ID'])"

cloudflare_api_token = "$($Vars['CLOUDFLARE_API_TOKEN'])"
cloudflare_zone_id   = "$($Vars['CLOUDFLARE_ZONE_ID'])"
app_subdomain        = "outreach"

ms_client_id     = "$($Vars['MS_CLIENT_ID'])"
ms_client_secret = "$($Vars['MS_CLIENT_SECRET'])"
"@

Set-Content -LiteralPath (Join-Path $EnvDir 'prod.tfvars') -Value $ProdTfvars
Write-Host 'wrote infra/envs/prod.tfvars'
Write-Host ''
Write-Host 'Bootstrap complete. Next: make dev or ./scripts/dev-docker.ps1.'
