#!/usr/bin/env bash
# Populates `.env.local` for LOCAL development from `.env.bootstrap`. Idempotent.
#
# Local development runs against a Docker Postgres 16 + Mailpit (see
# docker-compose.dev.yml) — no Supabase CLI, no cloud project. The only operator
# values consumed here are the Microsoft app-registration ones, which feed the
# Auth.js Entra provider (mapped to AZURE_AD_*). A local dev sign-in is also
# available via AUTH_MOCK_ENABLED without a Microsoft round-trip.
#
# Cloud/prod infrastructure values live in a separate step: `make bootstrap-prod`
# (scripts/bootstrap-prod.sh), which generates infra/envs/prod.tfvars.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOOTSTRAP="$ROOT/.env.bootstrap"

if [ ! -f "$BOOTSTRAP" ]; then
  echo "ERROR: $BOOTSTRAP not found. Copy .env.bootstrap.example or follow section 4.6 of the execution plan." >&2
  exit 1
fi

# shellcheck source=scripts/lib/load-dotenv.sh
. "$ROOT/scripts/lib/load-dotenv.sh"
load_dotenv "$BOOTSTRAP"

require() {
  local var="$1"
  if [ -z "${!var:-}" ]; then
    echo "ERROR: required variable $var is empty in .env.bootstrap" >&2
    echo "       (Local dev needs the Microsoft values for the Auth.js Entra provider.)" >&2
    exit 1
  fi
}

for v in MS_CLIENT_ID MS_CLIENT_SECRET MS_DEV_TENANT_ID; do
  require "$v"
done

# ─── .env.local (consumed by `next dev` and scripts/migrate.mjs) ────────────────
# The Postgres credentials below are the deterministic local-stack defaults
# (not secrets) — they match docker-compose.dev.yml.
cat > "$ROOT/.env.local" <<EOF
# AUTO-GENERATED by scripts/dev-bootstrap.sh. Do not edit by hand.
# Local Postgres 16 (docker-compose.dev.yml). The app connects as app_user;
# migrations connect as the postgres superuser (DATABASE_URL_ADMIN).
DATABASE_URL=postgres://app_user:apppw@localhost:5433/outreach
DATABASE_URL_ADMIN=postgres://postgres:postgres@localhost:5433/outreach
DATABASE_URL_TEST=postgres://app_user:apppw@localhost:5433/outreach
APP_USER_PASSWORD=apppw
# Local Postgres has no TLS; the migration runner honours PGSSL=disable in non-prod.
PGSSL=disable
# Auth.js (v5) + Microsoft Entra ID. AZURE_AD_* come from the .env.bootstrap MS_* app reg.
AUTH_SECRET=dev-insecure-local-secret
AZURE_AD_CLIENT_ID=$MS_CLIENT_ID
AZURE_AD_CLIENT_SECRET=$MS_CLIENT_SECRET
AZURE_AD_TENANT_ID=$MS_DEV_TENANT_ID
EMAIL_DRIVER=mailpit
# Public origin — also gates the dev mock backdoors (must be loopback to enable).
APP_BASE_URL=http://localhost:3000
# Local dev only: enables the /auth/mock dev sign-in. NODE_ENV=production ignores it.
AUTH_MOCK_ENABLED=true
EOF
echo "✓ wrote .env.local"

echo
echo "Local bootstrap complete. Next: \`make dev\`."
echo "For the prod cloud environment (Azure), run \`make bootstrap-prod\`."
