#!/usr/bin/env bash
# Populates `.env.local` for LOCAL development from `.env.bootstrap`. Idempotent.
#
# Local development needs NO Supabase cloud project and NO Vercel — the stack
# runs entirely on the local Supabase CLI (`supabase start`). The only operator
# values consumed here are the Microsoft app-registration ones, because the
# local Supabase Auth has the Azure provider enabled (see supabase/config.toml).
#
# Cloud/prod infrastructure values live in a separate step: `make bootstrap-prod`
# (scripts/bootstrap-prod.sh), which generates infra/envs/prod.tfvars.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOOTSTRAP="$ROOT/.env.bootstrap"

if [ ! -f "$BOOTSTRAP" ]; then
  echo "ERROR: $BOOTSTRAP not found. Copy .env.bootstrap.example or follow section 4.6 of the execution plan." >&2
  exit 1
fi

# shellcheck source=scripts/lib/load-dotenv.sh
. "$ROOT/scripts/lib/load-dotenv.sh"
load_dotenv "$BOOTSTRAP"

require() {
  local var="$1"
  if [ -z "${!var:-}" ]; then
    echo "ERROR: required variable $var is empty in .env.bootstrap" >&2
    echo "       (Local dev needs the Microsoft values so 'supabase start' can enable the Azure auth provider.)" >&2
    exit 1
  fi
}

for v in MS_CLIENT_ID MS_CLIENT_SECRET MS_DEV_TENANT_ID; do
  require "$v"
done

# ─── .env.local (consumed by `next dev` and `supabase start`) ───────────────────
# The Supabase URL and keys below are the deterministic local-stack defaults
# (not secrets) — no cloud project is involved.
cat > "$ROOT/.env.local" <<EOF
# AUTO-GENERATED by scripts/dev-bootstrap.sh. Do not edit by hand.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
MS_CLIENT_ID=$MS_CLIENT_ID
MS_CLIENT_SECRET=$MS_CLIENT_SECRET
MS_DEV_TENANT_ID=$MS_DEV_TENANT_ID
EMAIL_DRIVER=mailpit
# Local dev only: enables the /auth/mock dev sign-in. NODE_ENV=production ignores it.
AUTH_MOCK_ENABLED=true
EOF
echo "✓ wrote .env.local"

echo
echo "Local bootstrap complete. Next: \`make dev\` or \`make dev-docker\`."
echo "For the prod cloud environment (Supabase + Vercel), run \`make bootstrap-prod\`."
